/* eslint-disable @typescript-eslint/no-unused-expressions */
[
  {
    id: 'ImIXgqyS9GI',
    title: 'Freshbeat (Angel Heredia Remix)',
    artists: undefined,
    album: 'Taito Tikaro',
    duration: 422,
  },
  {
    id: 'AdawY4a2UhU',
    title: 'BACK TO THE FUTURE',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 364,
  },
  {
    id: 'FulC_552szE',
    title: 'Papi fighter',
    artists: undefined,
    album: 'Angel Heredia',
    duration: 414,
  },
  {
    id: 'xWZE0KqmvuE',
    title: 'BACK TO THE FUTURE',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 215,
  },
  {
    id: 'WV_CxheUOB4',
    title: 'Stop The Beat Original Mix',
    artists: 'Enigmatronic',
    album: 'Enigmatronic',
    duration: 495,
  },
  {
    id: 'jmcBRlP4jFg',
    title: 'Tabu',
    artists: undefined,
    album: 'Angel Heredia',
    duration: 369,
  },
  {
    id: '9zGo97coFts',
    title: 'SHUT UP!',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 218,
  },
  {
    id: 'Jqz818ta0XE',
    title: 'Grillo',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 371,
  },
  {
    id: '4HGQeTbyXmQ',
    title: 'SHUT UP!',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 367,
  },
  {
    id: '0C1bvd0_MKM',
    title: 'Balkanims',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 440,
  },
  {
    id: 'omf5tv64g3c',
    title: 'Esan (Orignal Mix)',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 380,
  },
  {
    id: 'jKFf9-UiFkQ',
    title: 'Feel It',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 371,
  },
  {
    id: 'kepnG40uN28',
    title: "I Can't Stop",
    artists: undefined,
    album: 'LARABELL',
    duration: 299,
  },
  {
    id: '4KQz16EyTbc',
    title: 'Enjoy This Sound',
    artists: undefined,
    album: 'Angel Heredia, Djahir Miranda',
    duration: 431,
  },
  {
    id: 'l_2EOr_mKPY',
    title: 'Cytronella',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 466,
  },
  {
    id: 'M5tDRtjlUrM',
    title: 'Josanhell',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 401,
  },
  {
    id: '0HLd9MSsVHU',
    title: 'Gubbins',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 344,
  },
  {
    id: 'niad3cuaBmU',
    title: "Can't Stop The Beat",
    artists: 'Plastic',
    album: 'Plastic',
    duration: 289,
  },
  {
    id: 'AD6xFlRrySc',
    title: 'Transitions',
    artists: 'Angel Heredia',
    album: 'Angel Heredia',
    duration: 373,
  },
  {
    id: 'FQjsAoeKSg8',
    title: 'Raf',
    artists: 'Sakib Rafsan',
    album: 'Sakib Rafsan',
    duration: 154,
  },
];
