const channels = {
  APP_READY: 'APP_READY',
  APP_CLOSE: 'APP_CLOSE',
  APP_RESTART: 'APP_RESTART',
  APP_GET_LOGS: 'APP_GET_LOG',

  CONFIG_GET_ALL: 'CONFIG_GET_ALL',
  CONFIG_GET: 'CONFIG_GET',
  CONFIG_SET: 'CONFIG_SET',

  PLAYBACK_PLAY: 'PLAYBACK_PLAY',
  PLAYBACK_PAUSE: 'PLAYBACK_PAUSE',
  PLAYBACK_STOP: 'PLAYBACK_STOP',
  PLAYBACK_PLAYPAUSE: 'PLAYBACK_PLAYPAUSE',
  PLAYBACK_PREVIOUS: 'PLAYBACK_PREVIOUS',
  PLAYBACK_NEXT: 'PLAYBACK_NEXT',
  PLAYBACK_TRACK_CHANGE: 'PLAYBACK_TRACK_CHANGE',

  SETTINGS_TOGGLE_SLEEP_BLOCKER: 'SETTINGS_TOGGLE_SLEEP_BLOCKER',

  THEME_GET_ID: 'THEME_GET_ID',
  THEME_SET_ID: 'THEME_SET_ID',
  THEME_APPLY: 'THEME_APPLY',
  THEME_GET: 'THEME_GET',

  DIALOG_MESSAGE_BOX: 'DIALOG_MESSAGE_BOX',
  DIALOG_OPEN: 'DIALOG_OPEN',

  MENU_GO_TO_LIBRARY: 'MENU_GO_TO_LIBRARY',
  MENU_GO_TO_PLAYLISTS: 'MENU_GO_TO_PLAYLISTS',
  MENU_GO_TO_SETTINGS: 'MENU_GO_TO_SETTINGS',
  MENU_FIX_TRACKS: 'MENU_FIX_TRACKS',
  MENU_TRACK_DETAIL: 'MENU_TRACK_DETAIL',
  MENU_TRACKS_REMOVE: 'MENU_TRACKS_REMOVE',

  TRKLIST_MENU_SHOW: 'TRKLIST_MENU_SHOW',
  PLAYLIST_MENU_SHOW: 'PLAYLIST_MENU_SHOW',
  COMMON_MENU_SHOW: 'COMMON_MENU_SHOW',

  TRACK_UPDATED: 'TRACK_UPDATED',
  CMD_PLAYLIST_NEW: 'CMD_PLAYLIST_NEW',
  CMD_TRACKS_PLAYLIST_ADD: 'CMD_TRACKS_PLAYLIST_ADD',
  CMD_TRACKS_PLAYLIST_REMOVE: 'CMD_TRACKS_PLAYLIST_REMOVE',
  CMD_TRACKS_LIBRARY_REMOVE: 'CMD_TRACKS_LIBRARY_REMOVE',
  CMD_TRACKS_DELETE: 'CMD_TRACKS_DELETE',
  CMD_TRACK_ARTIST_FIND: 'CMD_TRACK_ARTIST_FIND',
  CMD_TRACK_DETAIL: 'CMD_TRACK_DETAIL',
  CMD_FILENAME_TAGS: 'CMD_FIX_TAGS',
  CMD_FIND_CANDIDATES: 'CMD_FIND_CANDIDATES',
  CMD_ANALYZE_AUDIO: 'CMD_ANALYZE_AUDIO',

  CMD_PLAYLIST_RENAME: 'CMD_PLAYLIST_RENAME',
  CMD_PLAYLIST_DUPLICATE: 'CMD_PLAYLIST_DUPLICATE',
  CMD_PLAYLIST_EXPORT: 'CMD_PLAYLIST_EXPORT',
  CMD_PLAYLIST_REMOVE: 'CMD_PLAYLIST_REMOVE',

  COVER_GET: 'COVER_GET',
  FIX_TAGS: 'FIX_TAGS',
  FIND_TAG_CANDIDATES: 'FIND_TAG_CANDIDATES',
  APPLY_TAG_SELECTIONS: 'APPLY_TAG_SELECTIONS',

  LOGGER: 'LOGGER',

  TRACK_ALL: 'TRACK_ALL',
  TRACKS_ADD: 'TRACKS_ADD',
  TRACK_UPDATE: 'TRACK_UPDATE',
  TRACKS_REMOVE: 'TRACKS_REMOVE',
  TRACKS_BY_ID: 'TRACKS_BY_ID',
  TRACKS_BY_PATH: 'TRACKS_BY_PATH',
  TRACKS_DELETE: 'TRACKS_DELETE',
  TRACK_BY_ID: 'TRACK_BY_ID',
  TRACK_BY_PATH: 'TRACK_BY_PATH',
  TRACK_UPDATE_RATING: 'TRACK_UPDATE_RATING',
  TRACK_UPDATE_METADATA: 'TRACK_UPDATE_METADATA',

  PLAYLIST_ALL: 'PLAYLIST_ALL',
  PLAYLIST_ADD: 'PLAYLIST_ADD',
  PLAYLIST_RENAME: 'PLAYLIST_RENAME',
  PLAYLIST_REMOVE: 'PLAYLIST_REMOVE',
  PLAYLISTS_BY_ID: 'PLAYLISTS_BY_ID',
  PLAYLIST_BY_ID: 'PLAYLIST_BY_ID',
  PLAYLIST_SET_TRACKS: 'PLAYLIST_SET_TRACKS',
  PLAYLIST_REORDER_TRACKS: 'PLAYLIST_REORDER_TRACKS',

  // Prune Mode - To Delete Playlist
  PLAYLIST_TO_DELETE_GET: 'PLAYLIST_TO_DELETE_GET',
  PLAYLIST_TO_DELETE_ADD_TRACK: 'PLAYLIST_TO_DELETE_ADD_TRACK',
  PLAYLIST_TO_DELETE_REMOVE_TRACK: 'PLAYLIST_TO_DELETE_REMOVE_TRACK',
  PLAYLIST_TO_DELETE_CLEAR: 'PLAYLIST_TO_DELETE_CLEAR',

  // Preparation Mode - Set Preparation Playlist
  PLAYLIST_PREPARATION_GET: 'PLAYLIST_PREPARATION_GET',
  PLAYLIST_PREPARATION_ADD_TRACK: 'PLAYLIST_PREPARATION_ADD_TRACK',
  PLAYLIST_PREPARATION_REMOVE_TRACK: 'PLAYLIST_PREPARATION_REMOVE_TRACK',
  PLAYLIST_PREPARATION_CLEAR: 'PLAYLIST_PREPARATION_CLEAR',

  DB_RESET: 'DB_RESET',

  LIBRARY_IMPORT_TRACKS: 'LIBRARY_IMPORT_TRACKS',
  LIBRARY_LOOKUP: 'LIBRARY_LOOKUP',

  PLAYLISTS_RESOLVE_M3U: 'PLAYLISTS_RESOLVE_M3U',
  PLAYLIST_EXPORT: 'PLAYLIST_EXPORT',

  // Audio Analysis
  AUDIO_ANALYZE: 'AUDIO_ANALYZE',
  AUDIO_ANALYZE_BATCH: 'AUDIO_ANALYZE_BATCH',
  AUDIO_ANALYSIS_PROGRESS: 'AUDIO_ANALYSIS_PROGRESS',
  AUDIO_ANALYSIS_TRACK_COMPLETE: 'AUDIO_ANALYSIS_TRACK_COMPLETE',
};

export default channels;
